name: Page on Push

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install github-cli
      run: npm install gitbook-cli -g

    - name: Install Dependencies
      run: gitbook install

    - name: Build assets
      run: gitbook build
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: _book
      env:
        GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
